### PR TITLE
Add missing images from spec proposal

### PR DESCRIPTION
**Pull request by oyiptong**
The html page had missing images. This PR adds them back, taken from the proposal at https://w3c.github.io/webpayments/proposals/tokenized_cards.html

### CODE REVIEW

**Comment by oyiptong** [comment]
@ianbjacobs I'm having issues with the Repository Manager. Is that something you could look into?

**Comment by ianbjacobs** [comment]
Hi @oyiptong,

I have flipped the necessary bit on the W3C site, so the issue is gone.

I do have some thoughts on the images, so I'd like to request some work on them before we include them. Here are some notes:

1) They use different terminology than this and other specs. For example "buyer" instead of "payer".
2) I find they are a bit overwhelming if you don't already know how they work (which is my case, for example). 

For example, it seems there are a couple of phases that could usefully be pulled out of the issuer token image. Phase I is how the issuer gets a token to the payer. If the issuer provides the payment app to the payer, does the payer even need to know the full PAN? It looks in the image like the payer provides the PAN, but in an app from an issuer, that seems unnecessary. Maybe the payer identifies "This card" somehow, and the issuer's token provider provisions the payment app accordingly. But another question that we might want to address is whether the payment app "stores" the token or dynamically accesses it or it could work either way. 

Phase II is that the payer authorizes payment through the payment app, which sends the token to the merchant/payee, etc. I would also like to request clarification about what the image depicts. It sort of looks like the merchant gets the original PAN. But I doubt that's what's meant. Rather, doesn't the merchant/payee get the token, give it to their acquirer who then sends it on...and the last step is that the merchant is paid? So (1) should the diagram show the acquirer? [I think the acquirer is called out in the second diagram] and (2) should the diagram make clear that the last step is an exchange of funds and not an exchange of token?

I have similar comments on the second diagram:

a) Some terminology differs between diagram 1 and 2. (e.g., "Original card issuer" v. "Original funding instrument issuer").

b) Could we split into a provisioning phase and a usage phase? I realize that may not make sense in all cases (e.g., 1-time tokens).

Ian

**Comment by ianbjacobs** [comment]
I closed this in error while doing some repo branch management. How do I re-connect this PR to the gh-pages branch?

Ian

**Comment by ianbjacobs** [comment]
Actually, I've added the missing images...so should be ok now.
Ian

**Pull request closed without merging**
